import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bot, CircleUserRound, Coins, FileText, HeartPulse, Home, PawPrint, Plus, Sparkles, Trophy, Upload, X, Play, Square, ChevronRight, ShieldCheck } from 'lucide-react';
import './styles.css';

const DOG_IMAGE='https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85';
const CAT_IMAGE='https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=85';

const initialState={pet:null,walks:[],wellness:[],coins:0,transactions:[]};
function load(){try{return JSON.parse(localStorage.getItem('petcare-assist')||'null')||initialState}catch{return initialState}}
function save(s){localStorage.setItem('petcare-assist',JSON.stringify(s))}

function App(){
 const [state,setState]=useState(load); const [tab,setTab]=useState('home'); const [showPet,setShowPet]=useState(false); const [running,setRunning]=useState(false); const [seconds,setSeconds]=useState(0);
 useEffect(()=>save(state),[state]);
 useEffect(()=>{if(!running)return; const t=setInterval(()=>setSeconds(s=>s+1),1000); return()=>clearInterval(t)},[running]);
 const pet=state.pet;
 const totalMinutes=state.walks.reduce((a,w)=>a+w.minutes,0); const totalDistance=state.walks.reduce((a,w)=>a+w.distance,0);
 const score=useMemo(()=>Math.min(100,20+(Math.min(40,totalMinutes/3))+Math.min(25,state.wellness.length*5)+Math.min(15,state.walks.length*5)),[totalMinutes,state.wellness.length,state.walks.length]);
 const finishWalk=()=>{const minutes=Math.max(1,Math.round(seconds/60));const distance=Number((minutes*0.065).toFixed(2));const reward=Math.min(15,5+Math.floor(minutes/10)*2);const walk={id:Date.now(),minutes,distance,date:new Date().toISOString()};setState(s=>({...s,walks:[walk,...s.walks],coins:s.coins+reward,transactions:[{id:Date.now(),amount:reward,label:'Completed walk',date:new Date().toISOString()},...s.transactions]}));setRunning(false);setSeconds(0);setTab('activity')};
 return <div className="app-shell">
  <main className="app">
   {tab==='home'&&<Home pet={pet} coins={state.coins} score={score} walks={state.walks} onAdd={()=>setShowPet(true)} onWalk={()=>pet&&setRunning(true)} onNavigate={setTab}/>} 
   {tab==='pet'&&<PetScreen pet={pet} state={state} score={score} onAdd={()=>setShowPet(true)} onNavigate={setTab}/>} 
   {tab==='activity'&&<ActivityScreen pet={pet} walks={state.walks} totalMinutes={totalMinutes} totalDistance={totalDistance} running={running} seconds={seconds} onStart={()=>pet&&setRunning(true)} onFinish={finishWalk}/>} 
   {tab==='wellness'&&<Wellness state={state} pet={pet} setState={setState}/>} 
   {tab==='rewards'&&<Rewards state={state}/>} 
   {tab==='assistant'&&<Assistant pet={pet}/>} 
  </main>
  {running&&<WalkOverlay seconds={seconds} pet={pet} onFinish={finishWalk} onClose={()=>{setRunning(false);setSeconds(0)}}/>}
  <nav className="bottom-nav">{[[Home,'home','Home'],[PawPrint,'pet','My Pet'],[Activity,'activity','Activity'],[HeartPulse,'wellness','Wellness'],[Coins,'rewards','Rewards']].map(([Icon,id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={20}/><span>{label}</span></button>)}</nav>
  {showPet&&<PetModal onClose={()=>setShowPet(false)} onSave={p=>{setState(s=>({...s,pet:p}));setShowPet(false)}}/>}
 </div>
}

function Home({pet,coins,score,walks,onAdd,onWalk,onNavigate}){return <div className="screen home-screen"><header className="topbar"><div><span className="eyebrow">PETCARE ASSIST</span><h1>{pet?`Good day, ${pet.name}.`:'A better day for your pet.'}</h1></div><CircleUserRound size={25}/></header>
 {!pet?<section className="hero empty-hero"><div className="hero-image"><img src={DOG_IMAGE}/><span className="floating-paw"><PawPrint size={18}/></span></div><div><span className="eyebrow">YOUR PET JOURNEY</span><h2>Care that moves with you.</h2><p>Add your first pet to start tracking walks, wellness, and rewards.</p><button className="primary" onClick={onAdd}><Plus size={18}/> Add your pet</button></div></section>:<section className="hero pet-hero"><div className="hero-image"><img src={pet.image||DOG_IMAGE}/></div><div className="hero-copy"><span className="eyebrow">{pet.breed||pet.species}</span><h2>{pet.name}</h2><p>Your care & activity score is <b>{Math.round(score)}</b>.</p><button className="primary" onClick={onWalk}><Play size={17}/> Start a walk</button></div></section>}
 <div className="quick-grid"><Quick icon={Activity} title="Activity" value={walks.length?`${walks.length} walk${walks.length>1?'s':''}`:'No walks yet'} onClick={()=>onNavigate('activity')}/><Quick icon={Coins} title="Points" value={`${coins} coins`} onClick={()=>onNavigate('rewards')}/><Quick icon={HeartPulse} title="Wellness" value={pet?'Keep routines simple':'Add a pet'} onClick={()=>onNavigate('wellness')}/></div>
 <section className="section"><div className="section-head"><div><span className="eyebrow">YOUR SPACE</span><h3>Start where you are</h3></div><ChevronRight size={18}/></div><div className="empty-card"><Sparkles size={20}/><div><b>{pet?'Build a simple routine':'Nothing to manage yet'}</b><p>{pet?'A few small habits are enough. Your activity and care history will grow naturally.':'The app stays intentionally quiet until you add information.'}</p></div></div></section>
 </div>}
function Quick({icon:Icon,title,value,onClick}){return <button className="quick" onClick={onClick}><span className="icon-box"><Icon size={18}/></span><span><small>{title}</small><b>{value}</b></span><ChevronRight size={16}/></button>}

function PetScreen({pet,state,score,onAdd,onNavigate}){if(!pet)return <div className="screen centered"><div className="empty-illustration"><PawPrint size={34}/></div><h2>Your pet lives here.</h2><p>Add a profile to personalize activity, wellness, and rewards.</p><button className="primary" onClick={onAdd}><Plus size={18}/> Add pet</button></div>;
 return <div className="screen pet-screen"><div className="pet-cover"><img src={pet.image||DOG_IMAGE}/><div className="cover-shade"/><button className="backless">My Pet</button><div className="cover-info"><span>{pet.species} · {pet.breed||'Pet'}</span><h1>{pet.name}</h1></div></div><div className="pet-content"><div className="pet-stat-row"><div><b>{Math.round(score)}</b><span>Care score</span></div><div><b>{state.walks.length}</b><span>Walks</span></div><div><b>{state.coins}</b><span>Coins</span></div></div><div className="tabs"><button className="active">Overview</button><button onClick={()=>onNavigate('activity')}>Activity</button><button onClick={()=>onNavigate('wellness')}>Wellness</button></div><section className="section"><div className="section-head"><div><span className="eyebrow">OVERVIEW</span><h3>{pet.name}'s care</h3></div></div><div className="empty-card"><ShieldCheck size={20}/><div><b>{state.walks.length?'Activity is building':'Ready for the first record'}</b><p>{state.walks.length?'Keep logging normal routines to build a useful history.':'Your pet profile is ready. Start a walk or add a wellness routine.'}</p></div></div></section></div></div>}

function ActivityScreen({pet,walks,totalMinutes,totalDistance,running,seconds,onStart,onFinish}){return <div className="screen"><header className="page-head"><div><span className="eyebrow">ACTIVITY</span><h1>Walks with {pet?.name||'your pet'}</h1></div><Activity size={24}/></header>{!pet?<Empty title="Add a pet first" text="Walking statistics belong to a pet profile."/>:<><div className="metric-grid"><Metric value={`${totalMinutes}m`} label="Total time"/><Metric value={`${totalDistance.toFixed(2)} km`} label="Distance"/><Metric value={walks.length} label="Walks"/></div><div className="walk-card"><div className="walk-orbit"><PawPrint size={28}/></div><span className="eyebrow">TODAY</span><h2>{running?format(seconds):'Ready to move?'}</h2><p>{running?'Your walk is being timed. Finish when you are back.':'Start a walk and earn PetCare Points when it is completed.'}</p>{running?<button className="primary" onClick={onFinish}><Square size={16}/> Finish walk</button>:<button className="primary" onClick={onStart}><Play size={17}/> Start a walk</button>}</div><section className="section"><div className="section-head"><div><span className="eyebrow">HISTORY</span><h3>Recent walks</h3></div></div>{walks.length?walks.slice(0,5).map(w=><div className="list-row" key={w.id}><span className="icon-box"><Activity size={17}/></span><div><b>{w.minutes} min walk</b><p>{w.distance.toFixed(2)} km · {new Date(w.date).toLocaleDateString()}</p></div><span className="earned">+{Math.min(15,5+Math.floor(w.minutes/10)*2)}</span></div>):<Empty title="No walks recorded" text="Your first completed walk will appear here."/>}</section></>}</div>}
function Metric({value,label}){return <div className="metric"><b>{value}</b><span>{label}</span></div>}
function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function WalkOverlay({seconds,pet,onFinish,onClose}){return <div className="overlay"><div className="walk-sheet"><button className="close" onClick={onClose}><X/></button><img src={pet?.image||DOG_IMAGE}/><span className="eyebrow">WALK IN PROGRESS</span><h1>{format(seconds)}</h1><p>{pet?.name||'Your pet'} is out exploring.</p><button className="primary" onClick={onFinish}><Square size={16}/> Finish walk</button></div></div>}

function Wellness({state,pet,setState}){const [text,setText]=useState('');const add=()=>{if(!text.trim())return;setState(s=>({...s,wellness:[{id:Date.now(),text:text.trim(),date:new Date().toISOString()},...s.wellness]}));setText('')};return <div className="screen"><header className="page-head"><div><span className="eyebrow">HEALTH & WELLNESS</span><h1>{pet?`${pet.name}'s routine`:'Wellness'}</h1></div><HeartPulse size={24}/></header>{!pet?<Empty title="Your wellness space is empty" text="Add a pet to start keeping simple care notes and routines."/>:<><div className="wellness-card"><div className="wellness-ring"><HeartPulse size={25}/></div><div><span className="eyebrow">CARE NOTES</span><h2>Keep observations simple.</h2><p>Record what you notice. The app does not diagnose your pet.</p></div></div><div className="input-row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Add a care note..."/><button onClick={add}><Plus size={18}/></button></div><section className="section"><div className="section-head"><div><span className="eyebrow">YOUR NOTES</span><h3>Wellness journal</h3></div></div>{state.wellness.length?state.wellness.map(n=><div className="list-row" key={n.id}><span className="icon-box"><HeartPulse size={17}/></span><div><b>{n.text}</b><p>{new Date(n.date).toLocaleDateString()}</p></div></div>):<Empty title="No notes yet" text="Add a small observation when you want to remember it."/>}</section></>}</div>}

function Rewards({state}){return <div className="screen"><header className="page-head"><div><span className="eyebrow">REWARDS</span><h1>PetCare Points</h1></div><Coins size={24}/></header><div className="coin-card"><div className="coin-symbol"><Coins size={25}/></div><span>AVAILABLE</span><strong>{state.coins}</strong><p>Points earned from eligible activities.</p></div><section className="section"><div className="section-head"><div><span className="eyebrow">HOW IT WORKS</span><h3>Earn through care</h3></div></div><div className="reward-grid"><Reward icon={Activity} title="Complete a walk" text="Earn points after a completed walk."/><Reward icon={HeartPulse} title="Care routines" text="Future routines can award small bonuses."/><Reward icon={Trophy} title="Milestones" text="Reach goals to unlock achievements."/></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">HISTORY</span><h3>Point activity</h3></div></div>{state.transactions.length?state.transactions.map(t=><div className="list-row" key={t.id}><span className="icon-box"><Coins size={17}/></span><div><b>{t.label}</b><p>{new Date(t.date).toLocaleDateString()}</p></div><span className="earned">+{t.amount}</span></div>):<Empty title="No points yet" text="Complete your first eligible walk to start your balance."/>}</section><p className="fineprint">Prototype points have no cash value and are not insurance benefits.</p></div>}
function Reward({icon:Icon,title,text}){return <div className="reward"><span className="icon-box"><Icon size={17}/></span><b>{title}</b><p>{text}</p></div>}

function Assistant({pet}){const prompts=['Explain my pet document','What information is missing?','Help me prepare a claim'];return <div className="screen assistant"><header className="page-head"><div><span className="eyebrow">GEMINI ASSISTANT</span><h1>Ask about care</h1></div><Bot size={24}/></header><div className="assistant-hero"><div className="ai-icon"><Sparkles/></div><h2>Helpful, not diagnostic.</h2><p>Gemini can explain uploaded information and guide document workflows. It should never replace a veterinarian.</p></div><div className="prompt-list">{prompts.map(p=><button key={p}><Sparkles size={16}/>{p}<ChevronRight size={16}/></button>)}</div><div className="composer"><input placeholder={pet?'Ask about your pet documents...':'Add a pet to personalize the assistant'} disabled={!pet}/><button disabled={!pet}><Bot size={18}/></button></div></div>}
function Empty({title,text}){return <div className="empty-inline"><div className="empty-illustration"><PawPrint size={22}/></div><b>{title}</b><p>{text}</p></div>}
function PetModal({onClose,onSave}){const [name,setName]=useState('');const [species,setSpecies]=useState('Dog');const [breed,setBreed]=useState('');const [image,setImage]=useState(DOG_IMAGE);return <div className="overlay"><div className="modal"><button className="close" onClick={onClose}><X/></button><span className="eyebrow">NEW PET</span><h2>Create a pet profile</h2><div className="pet-picker"><img src={image}/><button onClick={()=>setImage(image===DOG_IMAGE?CAT_IMAGE:DOG_IMAGE)}>Change photo</button></div><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Milo"/></label><label>Species<select value={species} onChange={e=>setSpecies(e.target.value)}><option>Dog</option><option>Cat</option><option>Other</option></select></label><label>Breed <span>(optional)</span><input value={breed} onChange={e=>setBreed(e.target.value)} placeholder="e.g. Labrador"/></label><button className="primary full" disabled={!name.trim()} onClick={()=>onSave({name:name.trim(),species,breed,image})}>Create profile</button></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
