import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bot, CircleUserRound, Coins, FileText, HeartPulse, Home, PawPrint, Plus, Sparkles, Trophy, Upload, X, Play, Square, ChevronRight, ShieldCheck, CheckCircle2, AlertCircle, Send, ArrowUpRight } from 'lucide-react';
import { askAssistant, analyzeDocument } from './api';
import './styles.css';

const DOG_IMAGE='https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85';
const CAT_IMAGE='https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=85';
const initialState={pet:null,walks:[],wellness:[],coins:0,transactions:[],documents:[],claims:[]};
function load(){try{return JSON.parse(localStorage.getItem('petcare-assist')||'null')||initialState}catch{return initialState}}
function save(s){localStorage.setItem('petcare-assist',JSON.stringify(s))}

function App(){
 const [state,setState]=useState(load); const [tab,setTab]=useState('home'); const [showPet,setShowPet]=useState(false); const [running,setRunning]=useState(false); const [seconds,setSeconds]=useState(0);
 useEffect(()=>save(state),[state]);
 useEffect(()=>{if(!running)return; const t=setInterval(()=>setSeconds(s=>s+1),1000); return()=>clearInterval(t)},[running]);
 const pet=state.pet;
 const totalMinutes=state.walks.reduce((a,w)=>a+w.minutes,0); const totalDistance=state.walks.reduce((a,w)=>a+w.distance,0);
 const score=useMemo(()=>Math.min(100,20+Math.min(40,totalMinutes/3)+Math.min(25,state.wellness.length*5)+Math.min(15,state.walks.length*5)),[totalMinutes,state.wellness.length,state.walks.length]);
 const finishWalk=()=>{const minutes=Math.max(1,Math.round(seconds/60));const distance=Number((minutes*0.065).toFixed(2));const reward=Math.min(15,5+Math.floor(minutes/10)*2);const now=Date.now();const walk={id:now,minutes,distance,date:new Date().toISOString(),mode:'prototype-estimate'};setState(s=>({...s,walks:[walk,...s.walks],coins:s.coins+reward,transactions:[{id:now,amount:reward,label:'Completed walk',date:new Date().toISOString()},...s.transactions]}));setRunning(false);setSeconds(0);setTab('activity')};
 return <div className="app-shell"><main className="app">
  {tab==='home'&&<Home pet={pet} coins={state.coins} score={score} walks={state.walks} documents={state.documents} onAdd={()=>setShowPet(true)} onWalk={()=>pet&&setRunning(true)} onNavigate={setTab}/>} 
  {tab==='pet'&&<PetScreen pet={pet} state={state} score={score} onAdd={()=>setShowPet(true)} onNavigate={setTab}/>} 
  {tab==='activity'&&<ActivityScreen pet={pet} walks={state.walks} totalMinutes={totalMinutes} totalDistance={totalDistance} running={running} seconds={seconds} onStart={()=>pet&&setRunning(true)} onFinish={finishWalk}/>} 
  {tab==='wellness'&&<Wellness state={state} pet={pet} setState={setState}/>} 
  {tab==='rewards'&&<Rewards state={state}/>} 
  {tab==='documents'&&<Documents pet={pet} state={state} setState={setState}/>} 
  {tab==='assistant'&&<Assistant pet={pet}/>} 
 </main>
 {running&&<WalkOverlay seconds={seconds} pet={pet} onFinish={finishWalk} onClose={()=>{setRunning(false);setSeconds(0)}}/>}
 <nav className="bottom-nav">{[[Home,'home','Home'],[PawPrint,'pet','My Pet'],[Activity,'activity','Activity'],[HeartPulse,'wellness','Wellness'],[Coins,'rewards','Rewards']].map(([Icon,id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={20}/><span>{label}</span></button>)}</nav>
 {showPet&&<PetModal onClose={()=>setShowPet(false)} onSave={p=>{setState(s=>({...s,pet:p}));setShowPet(false)}}/>}
 </div>
}

function Home({pet,coins,score,walks,documents,onAdd,onWalk,onNavigate}){return <div className="screen home-screen"><header className="topbar"><div><span className="eyebrow">PETCARE ASSIST</span><h1>{pet?`Good day, ${pet.name}.`:'A better day for your pet.'}</h1></div><CircleUserRound size={25}/></header>
 {!pet?<section className="hero empty-hero"><div className="hero-image"><img src={DOG_IMAGE} alt="Dog"/><span className="floating-paw"><PawPrint size={18}/></span></div><div><span className="eyebrow">YOUR PET JOURNEY</span><h2>Care that moves with you.</h2><p>Add your first pet to start tracking walks, wellness, documents, and rewards.</p><button className="primary" onClick={onAdd}><Plus size={18}/> Add your pet</button></div></section>:<section className="hero pet-hero"><div className="hero-image"><img src={pet.image||DOG_IMAGE} alt={pet.name}/></div><div className="hero-copy"><span className="eyebrow">{pet.breed||pet.species}</span><h2>{pet.name}</h2><p>Your care & activity score is <b>{Math.round(score)}</b>.</p><button className="primary" onClick={onWalk}><Play size={17}/> Start a walk</button></div></section>}
 <div className="quick-grid"><Quick icon={Activity} title="Activity" value={walks.length?`${walks.length} walk${walks.length>1?'s':''}`:'No walks yet'} onClick={()=>onNavigate('activity')}/><Quick icon={FileText} title="Documents" value={documents.length?`${documents.length} saved`:'Add records'} onClick={()=>onNavigate('documents')}/><Quick icon={Coins} title="Points" value={`${coins} coins`} onClick={()=>onNavigate('rewards')}/><Quick icon={Bot} title="Assistant" value="Ask Gemini" onClick={()=>onNavigate('assistant')}/></div>
 <section className="section"><div className="section-head"><div><span className="eyebrow">YOUR SPACE</span><h3>Start where you are</h3></div></div><div className="empty-card"><Sparkles size={20}/><div><b>{pet?'Build a simple routine':'Nothing to manage yet'}</b><p>{pet?'Walks, observations and documents become useful history only when you add them.':'The app stays intentionally quiet until you add information.'}</p></div></div></section>
 </div>}
function Quick({icon:Icon,title,value,onClick}){return <button className="quick" onClick={onClick}><span className="icon-box"><Icon size={18}/></span><span><small>{title}</small><b>{value}</b></span><ChevronRight size={16}/></button>}

function PetScreen({pet,state,score,onAdd,onNavigate}){if(!pet)return <div className="screen centered"><div className="empty-illustration"><PawPrint size={34}/></div><h2>Your pet lives here.</h2><p>Add a profile to personalize activity, wellness, and rewards.</p><button className="primary" onClick={onAdd}><Plus size={18}/> Add pet</button></div>;
 return <div className="screen pet-screen"><div className="pet-cover"><img src={pet.image||DOG_IMAGE} alt={pet.name}/><div className="cover-shade"/><div className="cover-info"><span>{pet.species} · {pet.breed||'Pet'}</span><h1>{pet.name}</h1><small>{pet.ageText||'Age not added'}{pet.insuranceProvider?` · ${pet.insuranceProvider}`:''}</small></div></div><div className="pet-content"><div className="pet-stat-row"><div><b>{Math.round(score)}</b><span>Care score</span></div><div><b>{state.walks.length}</b><span>Walks</span></div><div><b>{state.coins}</b><span>Coins</span></div></div><div className="tabs"><button className="active">Overview</button><button onClick={()=>onNavigate('activity')}>Activity</button><button onClick={()=>onNavigate('wellness')}>Wellness</button><button onClick={()=>onNavigate('documents')}>Documents</button></div><section className="section"><div className="section-head"><div><span className="eyebrow">OVERVIEW</span><h3>{pet.name}'s care</h3></div></div><div className="empty-card"><ShieldCheck size={20}/><div><b>{state.walks.length?'Activity is building':'Ready for the first record'}</b><p>{state.walks.length?'Keep logging normal routines to build a useful history.':'Start a walk, add an observation, or upload a document.'}</p></div></div></section></div></div>}

function ActivityScreen({pet,walks,totalMinutes,totalDistance,running,seconds,onStart,onFinish}){return <div className="screen"><header className="page-head"><div><span className="eyebrow">ACTIVITY</span><h1>Walks with {pet?.name||'your pet'}</h1></div><Activity size={24}/></header>{!pet?<Empty title="Add a pet first" text="Walking statistics belong to a pet profile."/>:<><div className="metric-grid"><Metric value={`${totalMinutes}m`} label="Total time"/><Metric value={`${totalDistance.toFixed(2)} km`} label="Distance"/><Metric value={walks.length} label="Walks"/></div><div className="prototype-note"><AlertCircle size={16}/><span>Prototype mode: distance is estimated from the timer. GPS tracking is not active yet.</span></div><div className="walk-card"><div className="walk-orbit"><PawPrint size={28}/></div><span className="eyebrow">TODAY</span><h2>{running?format(seconds):'Ready to move?'}</h2><p>{running?'Your walk is being timed. Finish when you are back.':'Complete a walk to add activity history and eligible PetCare Points.'}</p>{running?<button className="primary" onClick={onFinish}><Square size={16}/> Finish walk</button>:<button className="primary" onClick={onStart}><Play size={17}/> Start a walk</button>}</div><section className="section"><div className="section-head"><div><span className="eyebrow">HISTORY</span><h3>Recent walks</h3></div></div>{walks.length?walks.slice(0,5).map(w=><div className="list-row" key={w.id}><span className="icon-box"><Activity size={17}/></span><div><b>{w.minutes} min walk</b><p>{w.distance.toFixed(2)} km · {new Date(w.date).toLocaleDateString()}</p></div><span className="earned">+{Math.min(15,5+Math.floor(w.minutes/10)*2)}</span></div>):<Empty title="No walks recorded" text="Your first completed walk will appear here."/>}</section></>}</div>}
function Metric({value,label}){return <div className="metric"><b>{value}</b><span>{label}</span></div>}
function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function WalkOverlay({seconds,pet,onFinish,onClose}){return <div className="overlay"><div className="walk-sheet"><button className="close" onClick={onClose}><X/></button><img src={pet?.image||DOG_IMAGE} alt={pet?.name||'Pet'}/><span className="eyebrow">WALK IN PROGRESS</span><h1>{format(seconds)}</h1><p>{pet?.name||'Your pet'} is out exploring.</p><button className="primary" onClick={onFinish}><Square size={16}/> Finish walk</button></div></div>}

function Wellness({state,pet,setState}){const [text,setText]=useState('');const add=()=>{if(!text.trim())return;setState(s=>({...s,wellness:[{id:Date.now(),text:text.trim(),date:new Date().toISOString()},...s.wellness]}));setText('')};return <div className="screen"><header className="page-head"><div><span className="eyebrow">HEALTH & WELLNESS</span><h1>{pet?`${pet.name}'s routine`:'Wellness'}</h1></div><HeartPulse size={24}/></header>{!pet?<Empty title="Your wellness space is empty" text="Add a pet to start keeping simple care notes and routines."/>:<><div className="wellness-card"><div className="wellness-ring"><HeartPulse size={25}/></div><div><span className="eyebrow">CARE NOTES</span><h2>Keep observations simple.</h2><p>Record what you notice. The app does not diagnose your pet.</p></div></div><div className="input-row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Add a care note..."/><button onClick={add}><Plus size={18}/></button></div><section className="section"><div className="section-head"><div><span className="eyebrow">YOUR NOTES</span><h3>Wellness journal</h3></div></div>{state.wellness.length?state.wellness.map(n=><div className="list-row" key={n.id}><span className="icon-box"><HeartPulse size={17}/></span><div><b>{n.text}</b><p>{new Date(n.date).toLocaleDateString()}</p></div></div>):<Empty title="No notes yet" text="Add a small observation when you want to remember it."/>}</section></>}</div>}

function Rewards({state}){return <div className="screen"><header className="page-head"><div><span className="eyebrow">REWARDS</span><h1>PetCare Points</h1></div><Coins size={24}/></header><div className="coin-card"><div className="coin-symbol"><Coins size={25}/></div><span>AVAILABLE</span><strong>{state.coins}</strong><p>Points earned from eligible prototype activities.</p></div><section className="section"><div className="section-head"><div><span className="eyebrow">HOW IT WORKS</span><h3>Earn through care</h3></div></div><div className="reward-grid"><Reward icon={Activity} title="Complete a walk" text="Eligible completed walks can award points."/><Reward icon={HeartPulse} title="Care routines" text="Routine bonuses can be added later."/><Reward icon={Trophy} title="Milestones" text="Milestone rewards are planned for the next layer."/></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">HISTORY</span><h3>Point activity</h3></div></div>{state.transactions.length?state.transactions.map(t=><div className="list-row" key={t.id}><span className="icon-box"><Coins size={17}/></span><div><b>{t.label}</b><p>{new Date(t.date).toLocaleDateString()}</p></div><span className="earned">+{t.amount}</span></div>):<Empty title="No points yet" text="Complete your first eligible walk to start your balance."/>}</section><p className="fineprint">Prototype points have no cash value and are not insurance benefits.</p></div>}
function Reward({icon:Icon,title,text}){return <div className="reward"><span className="icon-box"><Icon size={17}/></span><b>{title}</b><p>{text}</p></div>}

function Assistant({pet}){const prompts=['Explain my pet document','What information is missing?','Help me prepare a claim'];const [message,setMessage]=useState('');const [messages,setMessages]=useState([]);const [busy,setBusy]=useState(false);const send=async text=>{const value=(text||message).trim();if(!value||busy)return;setMessage('');setMessages(m=>[...m,{role:'user',text:value}]);setBusy(true);try{const reply=await askAssistant(value,pet);setMessages(m=>[...m,{role:'assistant',text:reply}])}catch(error){setMessages(m=>[...m,{role:'assistant',text:error.message}])}finally{setBusy(false)}};return <div className="screen assistant"><header className="page-head"><div><span className="eyebrow">GEMINI ASSISTANT</span><h1>Ask about care</h1></div><Bot size={24}/></header><div className="assistant-hero"><div className="ai-icon"><Sparkles/></div><h2>Helpful, not diagnostic.</h2><p>Ask about documents, missing information, or how to organize a claim. Gemini does not diagnose or replace veterinary care.</p></div>{!messages.length&&<div className="prompt-list">{prompts.map(p=><button key={p} onClick={()=>send(p)}><Sparkles size={16}/>{p}<ChevronRight size={16}/></button>)}</div>}<div className="message-list">{messages.map((m,i)=><div className={`chat-bubble ${m.role}`} key={i}><span>{m.role==='assistant'?'Gemini':'You'}</span><p>{m.text}</p></div>)}{busy&&<div className="chat-bubble assistant"><span>Gemini</span><p>Thinking…</p></div>}</div><div className="composer"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder={pet?'Ask about your pet documents...':'Add a pet to personalize the assistant'} disabled={!pet||busy}/><button onClick={()=>send()} disabled={!pet||busy||!message.trim()}><Send size={18}/></button></div></div>}

function Documents({pet,state,setState}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [selected,setSelected]=useState(null);const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const result=await analyzeDocument(file,pet);const doc={id:Date.now(),fileName:file.name,mimeType:file.type,date:new Date().toISOString(),analysis:result,verified:false};setState(s=>({...s,documents:[doc,...s.documents]}));setSelected(doc)}catch(err){setError(err.message)}finally{setBusy(false);e.target.value=''}};return <div className="screen"><header className="page-head"><div><span className="eyebrow">DOCUMENTS</span><h1>Pet records</h1></div><FileText size={24}/></header>{!pet?<Empty title="Add a pet first" text="Documents are linked to a pet profile so extracted information has context."/>:<><label className={`upload-card ${busy?'busy':''}`}><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={upload} disabled={busy}/><span className="upload-icon">{busy?<Sparkles/>:<Upload/>}</span><div><b>{busy?'Analyzing document…':'Upload a vet document'}</b><p>PDF, JPG, PNG or WebP. Gemini will extract visible information for your review.</p></div><ArrowUpRight size={18}/></label>{error&&<div className="error-banner"><AlertCircle size={16}/>{error}</div>}<section className="section"><div className="section-head"><div><span className="eyebrow">YOUR RECORDS</span><h3>Uploaded documents</h3></div></div>{state.documents.length?state.documents.map(d=><button className="document-row" key={d.id} onClick={()=>setSelected(d)}><span className="icon-box"><FileText size={17}/></span><div><b>{d.fileName}</b><p>{d.analysis?.document_type||'Pet document'} · {new Date(d.date).toLocaleDateString()}</p></div><span className={d.verified?'verified':'unverified'}>{d.verified?'Verified':'Review'}</span></button>):<Empty title="No documents yet" text="Upload a vet invoice, record, or other supported pet document."/>}</section>{selected&&<DocumentReview doc={selected} onClose={()=>setSelected(null)} onVerify={()=>{setState(s=>({...s,documents:s.documents.map(d=>d.id===selected.id?{...d,verified:true}:d)}));setSelected({...selected,verified:true})}}/>}</>}</div>}
function DocumentReview({doc,onClose,onVerify}){const a=doc.analysis||{};return <div className="overlay"><div className="modal document-modal"><button className="close" onClick={onClose}><X/></button><span className="eyebrow">AI EXTRACTION</span><h2>{a.document_type||'Document review'}</h2><p>{a.summary}</p><div className="review-section"><b>Extracted information</b>{Object.entries(a.extracted_fields||{}).map(([k,v])=><div className="review-row" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v||'Not found'}</strong></div>)}</div>{(a.missing_information||[]).length>0&&<div className="review-section"><b>Missing information</b>{a.missing_information.map(x=><div className="review-bullet" key={x}><AlertCircle size={15}/>{x}</div>)}</div>} {(a.uncertain_information||[]).length>0&&<div className="review-section"><b>Needs review</b>{a.uncertain_information.map(x=><div className="review-bullet" key={x}><AlertCircle size={15}/>{x}</div>)}</div>}<div className="verification-box"><CheckCircle2 size={18}/><span>AI extraction is not verified until you review it.</span></div><button className="primary" onClick={onVerify} disabled={doc.verified}>{doc.verified?'Verified':'I reviewed this information'}</button></div></div>}

function Empty({title,text}){return <div className="empty-inline"><div className="empty-illustration"><PawPrint size={22}/></div><b>{title}</b><p>{text}</p></div>}
function PetModal({onClose,onSave}){const [name,setName]=useState('');const [species,setSpecies]=useState('Dog');const [breed,setBreed]=useState('');const [dob,setDob]=useState('');const [insuranceProvider,setInsuranceProvider]=useState('');const [image,setImage]=useState(DOG_IMAGE);const ageText=dob?calculateAge(dob):'';return <div className="overlay"><div className="modal"><button className="close" onClick={onClose}><X/></button><span className="eyebrow">NEW PET</span><h2>Create a pet profile</h2><div className="pet-picker"><img src={image} alt="Pet preview"/><button onClick={()=>setImage(image===DOG_IMAGE?CAT_IMAGE:DOG_IMAGE)}>Change photo</button></div><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Milo"/></label><label>Species<select value={species} onChange={e=>setSpecies(e.target.value)}><option>Dog</option><option>Cat</option><option>Other</option></select></label><label>Breed <span>(optional)</span><input value={breed} onChange={e=>setBreed(e.target.value)} placeholder="e.g. Labrador"/></label><label>Date of birth <span>(optional)</span><input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><label>Insurance provider <span>(optional)</span><input value={insuranceProvider} onChange={e=>setInsuranceProvider(e.target.value)} placeholder="e.g. Pet insurer"/></label><button className="primary" disabled={!name.trim()} onClick={()=>onSave({id:Date.now(),name:name.trim(),species,breed:breed.trim(),dob,ageText,insuranceProvider:insuranceProvider.trim(),image})}>Save pet</button></div></div>}
function calculateAge(dob){const birth=new Date(dob);if(Number.isNaN(birth.getTime()))return '';const now=new Date();let years=now.getFullYear()-birth.getFullYear();let months=now.getMonth()-birth.getMonth();if(now.getDate()<birth.getDate())months--;if(months<0){years--;months+=12}return years>0?`${years}y ${months}m old`:`${Math.max(0,months)}m old`}

createRoot(document.getElementById('root')).render(<App/>);
