import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bot, CircleUserRound, Coins, FileText, HeartPulse, Home, PawPrint, Plus, Sparkles, Trophy, Upload, X, Play, Square, ChevronRight, ShieldCheck, MapPin, CheckCircle2, Clock3, ClipboardCheck } from 'lucide-react';
import { askAssistant, analyzeDocument } from './api';
import { createGpsTracker } from './activity';
import { calculateCareScore, scoreLabel } from './score';
import './styles.css';

const DOG_IMAGE='https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85';
const CAT_IMAGE='https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=85';
const initialState={pet:null,walks:[],wellness:[],careTasks:[],coins:0,transactions:[],documents:[],claims:[]};
function load(){try{return {...initialState,...JSON.parse(localStorage.getItem('petcare-assist')||'{}')}}catch{return initialState}}
function save(s){localStorage.setItem('petcare-assist',JSON.stringify(s))}

function App(){
 const [state,setState]=useState(load); const [tab,setTab]=useState('home'); const [showPet,setShowPet]=useState(false); const [running,setRunning]=useState(false); const [seconds,setSeconds]=useState(0); const [gpsDistance,setGpsDistance]=useState(0); const [gpsError,setGpsError]=useState(''); const [stopGps,setStopGps]=useState(null);
 useEffect(()=>save(state),[state]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[running]);
 useEffect(()=>()=>stopGps?.(),[stopGps]);
 const pet=state.pet; const totalMinutes=state.walks.reduce((a,w)=>a+w.minutes,0); const totalDistance=state.walks.reduce((a,w)=>a+w.distance,0);
 const score=useMemo(()=>calculateCareScore(state),[state]);
 const startWalk=()=>{if(!pet)return;setGpsDistance(0);setGpsError('');setSeconds(0);setRunning(true);try{const stop=createGpsTracker(({distance})=>setGpsDistance(distance),err=>setGpsError(err.code===1?'Location permission was denied. You can still log the walk manually.':'GPS is unavailable. The walk will use manual timing.'));setStopGps(()=>stop)}catch(e){setGpsError(e.message)}};
 const finishWalk=()=>{const minutes=Math.max(1,Math.round(seconds/60));const distance=gpsDistance>0?Number(gpsDistance.toFixed(2)):Number((minutes*0.065).toFixed(2));const reward=Math.min(15,5+Math.floor(minutes/10)*2);const now=Date.now();const walk={id:now,minutes,distance,date:new Date().toISOString(),mode:gpsDistance>0?'gps':'manual-estimate'};setState(s=>({...s,walks:[walk,...s.walks],coins:s.coins+reward,transactions:[{id:now,amount:reward,label:'Completed walk',date:new Date().toISOString()},...s.transactions]}));stopGps?.();setStopGps(null);setRunning(false);setSeconds(0);setGpsDistance(0);setTab('activity')};
 return <div className="app-shell"><main className="app">
  {tab==='home'&&<Home pet={pet} coins={state.coins} score={score} walks={state.walks} onAdd={()=>setShowPet(true)} onWalk={startWalk} onNavigate={setTab}/>} 
  {tab==='pet'&&<PetScreen pet={pet} state={state} score={score} onAdd={()=>setShowPet(true)} onNavigate={setTab}/>} 
  {tab==='activity'&&<ActivityScreen pet={pet} walks={state.walks} totalMinutes={totalMinutes} totalDistance={totalDistance} running={running} seconds={seconds} gpsDistance={gpsDistance} gpsError={gpsError} onStart={startWalk} onFinish={finishWalk}/>} 
  {tab==='wellness'&&<Wellness state={state} pet={pet} setState={setState}/>} 
  {tab==='rewards'&&<Rewards state={state}/>} 
  {tab==='documents'&&<Documents pet={pet} state={state} setState={setState}/>} 
  {tab==='assistant'&&<Assistant pet={pet}/>} 
 </main>{running&&<WalkOverlay seconds={seconds} distance={gpsDistance} pet={pet} gpsError={gpsError} onFinish={finishWalk} onClose={()=>{stopGps?.();setStopGps(null);setRunning(false);setSeconds(0);setGpsDistance(0)}}/>}
 <nav className="bottom-nav">{[[Home,'home','Home'],[PawPrint,'pet','My Pet'],[Activity,'activity','Activity'],[HeartPulse,'wellness','Wellness'],[Coins,'rewards','Rewards']].map(([Icon,id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={20}/><span>{label}</span></button>)}</nav>
 {showPet&&<PetModal onClose={()=>setShowPet(false)} onSave={p=>{setState(s=>({...s,pet:p}));setShowPet(false)}}/>}</div>
}

function Home({pet,coins,score,walks,onAdd,onWalk,onNavigate}){return <div className="screen"><header className="topbar"><div><span className="eyebrow">PETCARE ASSIST</span><h1>{pet?`Good day, ${pet.name}.`:'A better day for your pet.'}</h1></div><CircleUserRound size={25}/></header>{!pet?<section className="hero empty-hero"><div className="hero-image"><img src={DOG_IMAGE} alt="Dog"/></div><div><span className="eyebrow">YOUR PET JOURNEY</span><h2>Care that moves with you.</h2><p>Add your first pet to start tracking activity, wellness, documents, and rewards.</p><button className="primary" onClick={onAdd}><Plus size={18}/> Add your pet</button></div></section>:<section className="hero pet-hero"><div className="hero-image"><img src={pet.image||DOG_IMAGE} alt={pet.name}/></div><div className="hero-copy"><span className="eyebrow">{pet.breed||pet.species}</span><h2>{pet.name}</h2><p>{score===null?'Not enough activity data':`${Math.round(score)} · ${scoreLabel(score)}`}</p><button className="primary" onClick={onWalk}><Play size={17}/> Start a walk</button></div></section>}
 <div className="quick-grid"><Quick icon={Activity} title="Activity" value={walks.length?`${walks.length} walks`:'No walks yet'} onClick={()=>onNavigate('activity')}/><Quick icon={FileText} title="Documents" value="Upload records" onClick={()=>onNavigate('documents')}/><Quick icon={Coins} title="Points" value={`${coins} coins`} onClick={()=>onNavigate('rewards')}/><Quick icon={Bot} title="Assistant" value="Ask Gemini" onClick={()=>onNavigate('assistant')}/></div>
 <section className="section"><div className="section-head"><div><span className="eyebrow">CARE SNAPSHOT</span><h3>Small records become useful history</h3></div></div><div className="empty-card"><Sparkles size={20}/><div><b>{pet?'Keep building the routine':'Nothing to manage yet'}</b><p>{pet?'Walks, care notes and documents are kept together so you can review them later.':'The app stays quiet until you add real information.'}</p></div></div></section></div>}
function Quick({icon:Icon,title,value,onClick}){return <button className="quick" onClick={onClick}><span className="icon-box"><Icon size={18}/></span><span><small>{title}</small><b>{value}</b></span><ChevronRight size={16}/></button>}

function PetScreen({pet,state,score,onAdd,onNavigate}){if(!pet)return <div className="screen centered"><div className="empty-illustration"><PawPrint size={34}/></div><h2>Your pet lives here.</h2><p>Add a profile to personalize activity, wellness, documents, and rewards.</p><button className="primary" onClick={onAdd}><Plus size={18}/> Add pet</button></div>;return <div className="screen pet-screen"><div className="pet-cover"><img src={pet.image||DOG_IMAGE} alt={pet.name}/><div className="cover-shade"/><div className="cover-info"><span>{pet.species} · {pet.breed||'Pet'}</span><h1>{pet.name}</h1><small>{pet.ageText||'Age not added'}{pet.insuranceProvider?` · ${pet.insuranceProvider}`:''}</small></div></div><div className="pet-content"><div className="pet-stat-row"><div><b>{score===null?'—':Math.round(score)}</b><span>Care score</span></div><div><b>{state.walks.length}</b><span>Walks</span></div><div><b>{state.coins}</b><span>Coins</span></div></div><div className="tabs"><button className="active">Overview</button><button onClick={()=>onNavigate('activity')}>Activity</button><button onClick={()=>onNavigate('wellness')}>Wellness</button><button onClick={()=>onNavigate('documents')}>Documents</button></div><section className="section"><div className="section-head"><div><span className="eyebrow">OVERVIEW</span><h3>{pet.name}'s care</h3></div></div><div className="empty-card"><ShieldCheck size={20}/><div><b>{score===null?'Ready for the first record':scoreLabel(score)}</b><p>{score===null?'Start a walk, add an observation, or upload a document.':'The score is a wellness/activity indicator, not a medical assessment.'}</p></div></div></section></div></div>}

function ActivityScreen({pet,walks,totalMinutes,totalDistance,running,seconds,gpsDistance,gpsError,onStart,onFinish}){return <div className="screen"><header className="page-head"><div><span className="eyebrow">ACTIVITY</span><h1>Walks with {pet?.name||'your pet'}</h1></div><Activity size={24}/></header>{!pet?<Empty title="Add a pet first" text="Walking statistics belong to a pet profile."/>:<><div className="metric-grid"><Metric value={`${totalMinutes}m`} label="Total time"/><Metric value={`${totalDistance.toFixed(2)} km`} label="Distance"/><Metric value={walks.length} label="Walks"/></div><div className="walk-card"><div className="walk-orbit"><MapPin size={28}/></div><span className="eyebrow">{running?'LIVE WALK':'READY'}</span><h2>{running?format(seconds):'Ready to move?'}</h2><p>{running?`${gpsDistance.toFixed(2)} km recorded by GPS when available.`:'GPS is used when your browser grants location access. Otherwise the walk is saved as a manual estimate.'}</p>{gpsError&&<div className="notice">{gpsError}</div>}{running?<button className="primary" onClick={onFinish}><Square size={16}/> Finish walk</button>:<button className="primary" onClick={onStart}><Play size={17}/> Start a walk</button>}</div><section className="section"><div className="section-head"><div><span className="eyebrow">HISTORY</span><h3>Recent walks</h3></div></div>{walks.length?walks.slice(0,7).map(w=><div className="list-row" key={w.id}><span className="icon-box"><Activity size={17}/></span><div><b>{w.minutes} min walk</b><p>{w.distance.toFixed(2)} km · {w.mode==='gps'?'GPS':'manual estimate'} · {new Date(w.date).toLocaleDateString()}</p></div><span className="earned">+{Math.min(15,5+Math.floor(w.minutes/10)*2)}</span></div>):<Empty title="No walks recorded" text="Your first completed walk will appear here."/>}</section></>}</div>}
function Metric({value,label}){return <div className="metric"><b>{value}</b><span>{label}</span></div>}
function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function WalkOverlay({seconds,distance,pet,gpsError,onFinish,onClose}){return <div className="overlay"><div className="walk-sheet"><button className="close" onClick={onClose}><X/></button><img src={pet?.image||DOG_IMAGE} alt={pet?.name||'Pet'}/><span className="eyebrow">WALK IN PROGRESS</span><h1>{format(seconds)}</h1><div className="live-distance"><MapPin size={16}/> {distance.toFixed(2)} km</div>{gpsError&&<p className="small-note">{gpsError}</p>}<p>{pet?.name||'Your pet'} is out exploring.</p><button className="primary" onClick={onFinish}><Square size={16}/> Finish walk</button></div></div>}

function Wellness({state,pet,setState}){const [text,setText]=useState('');const [task,setTask]=useState('');const addNote=()=>{if(!text.trim())return;setState(s=>({...s,wellness:[{id:Date.now(),text:text.trim(),date:new Date().toISOString()},...s.wellness]}));setText('')};const addTask=()=>{if(!task.trim())return;setState(s=>({...s,careTasks:[{id:Date.now(),title:task.trim(),completed:false},...s.careTasks]}));setTask('')};const toggle=id=>setState(s=>({...s,careTasks:s.careTasks.map(t=>t.id===id?{...t,completed:!t.completed}:t)}));return <div className="screen"><header className="page-head"><div><span className="eyebrow">HEALTH & WELLNESS</span><h1>{pet?`${pet.name}'s routine`:'Wellness'}</h1></div><HeartPulse size={24}/></header>{!pet?<Empty title="Your wellness space is empty" text="Add a pet to start keeping simple care notes and routines."/>:<><div className="wellness-card"><div className="wellness-ring"><HeartPulse size={25}/></div><div><span className="eyebrow">CARE NOTES</span><h2>Keep observations simple.</h2><p>Record what you notice. PetCare Assist does not diagnose your pet.</p></div></div><section className="section"><div className="section-head"><div><span className="eyebrow">ROUTINES</span><h3>Care tasks</h3></div></div><div className="input-row"><input value={task} onChange={e=>setTask(e.target.value)} placeholder="e.g. Brush coat"/><button onClick={addTask}><Plus size={18}/></button></div>{state.careTasks.length?state.careTasks.map(t=><button className="task-row" key={t.id} onClick={()=>toggle(t.id)}><span className={t.completed?'task-check done':'task-check'}>{t.completed&&<CheckCircle2 size={18}/>}</span><span>{t.title}</span></button>):<Empty title="No routines yet" text="Add simple recurring care tasks you want to remember."/>}</section><section className="section"><div className="section-head"><div><span className="eyebrow">JOURNAL</span><h3>Wellness observations</h3></div></div><div className="input-row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Add a care note..."/><button onClick={addNote}><Plus size={18}/></button></div>{state.wellness.length?state.wellness.map(n=><div className="list-row" key={n.id}><span className="icon-box"><HeartPulse size={17}/></span><div><b>{n.text}</b><p>{new Date(n.date).toLocaleDateString()}</p></div></div>):<Empty title="No observations yet" text="Add a small note when you want to remember something."/>}</section></>}</div>}

function Rewards({state}){return <div className="screen"><header className="page-head"><div><span className="eyebrow">REWARDS</span><h1>PetCare Points</h1></div><Coins size={24}/></header><div className="coin-card"><div className="coin-symbol"><Coins size={25}/></div><span>AVAILABLE</span><strong>{state.coins}</strong><p>Prototype points earned from eligible activities.</p></div><section className="section"><div className="section-head"><div><span className="eyebrow">EARN</span><h3>How points work</h3></div></div><div className="reward-grid"><Reward icon={Activity} title="Complete a walk" text="Completed walks can award points, with a small cap per walk."/><Reward icon={ClipboardCheck} title="Complete care tasks" text="Routine bonuses can be added once the reward rules are finalized."/><Reward icon={Trophy} title="Milestones" text="Future milestones can unlock partner rewards."/></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">HISTORY</span><h3>Point activity</h3></div></div>{state.transactions.length?state.transactions.map(t=><div className="list-row" key={t.id}><span className="icon-box"><Coins size={17}/></span><div><b>{t.label}</b><p>{new Date(t.date).toLocaleDateString()}</p></div><span className="earned">+{t.amount}</span></div>):<Empty title="No points yet" text="Complete your first eligible walk to start your balance."/>}</section><p className="fineprint">Prototype points have no cash value and are not insurance benefits. Real-world rewards require a verified partner and redemption system.</p></div>}
function Reward({icon:Icon,title,text}){return <div className="reward"><span className="icon-box"><Icon size={17}/></span><b>{title}</b><p>{text}</p></div>}

function Documents({pet,state,setState}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState(null);const handle=async e=>{const file=e.target.files?.[0];if(!file)return;if(!pet){setError('Add a pet before uploading a document.');return}setBusy(true);setError('');setResult(null);try{const data=await analyzeDocument(file,pet);const doc={id:Date.now(),name:file.name,type:data.document_type,summary:data.summary,fields:data.extracted_fields||{},missing:data.missing_information||[],uncertain:data.uncertain_information||[],verified:false,date:new Date().toISOString()};setState(s=>({...s,documents:[doc,...s.documents]}));setResult(doc)}catch(err){setError(err.message)}finally{setBusy(false);e.target.value=''}};const verify=id=>setState(s=>({...s,documents:s.documents.map(d=>d.id===id?{...d,verified:true}:d)}));return <div className="screen"><header className="page-head"><div><span className="eyebrow">DOCUMENTS</span><h1>Pet records</h1></div><FileText size={24}/></header>{!pet?<Empty title="Add a pet first" text="Documents are attached to a pet profile."/>:<><label className="upload-box"><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={handle}/><Upload size={22}/><b>{busy?'Analyzing with Gemini...':'Upload a vet document'}</b><span>PDF, JPG, PNG or WebP</span></label>{error&&<div className="notice error">{error}</div>}{result&&<DocumentReview doc={result} onVerify={()=>verify(result.id)}/>}<section className="section"><div className="section-head"><div><span className="eyebrow">SAVED RECORDS</span><h3>Your documents</h3></div></div>{state.documents.length?state.documents.map(d=><DocumentRow key={d.id} doc={d}/>):<Empty title="No documents yet" text="Upload a vet invoice, receipt, record, or other relevant document."/>}</section></>}</div>}
function DocumentReview({doc,onVerify}){return <div className="review-card"><div className="review-head"><div><span className="eyebrow">AI EXTRACTION</span><h3>{doc.type||'Document'}</h3></div><span className={doc.verified?'verified':'unverified'}>{doc.verified?'Verified':'Needs review'}</span></div><p>{doc.summary}</p>{Object.entries(doc.fields).map(([k,v])=><div className="field-row" key={k}><span>{k.replaceAll('_',' ')}</span><b>{v}</b></div>)}{!!doc.missing.length&&<div className="notice"><b>Missing:</b> {doc.missing.join(', ')}</div>}{!!doc.uncertain.length&&<div className="notice"><b>Uncertain:</b> {doc.uncertain.join(', ')}</div>} {!doc.verified&&<button className="primary full" onClick={onVerify}><CheckCircle2 size={17}/> I reviewed this information</button>}</div>}
function DocumentRow({doc}){return <div className="list-row"><span className="icon-box"><FileText size={17}/></span><div><b>{doc.name}</b><p>{doc.type||'Document'} · {doc.verified?'Verified':'Needs review'}</p></div><ChevronRight size={16}/></div>}

function Assistant({pet}){const prompts=['Explain my pet document','What information is missing?','Help me prepare a claim'];const [message,setMessage]=useState('');const [messages,setMessages]=useState([]);const [busy,setBusy]=useState(false);const send=async text=>{const value=(text||message).trim();if(!value||busy||!pet)return;setMessage('');setMessages(m=>[...m,{role:'user',text:value}]);setBusy(true);try{const reply=await askAssistant(value,pet);setMessages(m=>[...m,{role:'assistant',text:reply}])}catch(e){setMessages(m=>[...m,{role:'assistant',text:e.message}])}finally{setBusy(false)}};return <div className="screen assistant"><header className="page-head"><div><span className="eyebrow">GEMINI ASSISTANT</span><h1>Ask about care</h1></div><Bot size={24}/></header><div className="assistant-hero"><div className="ai-icon"><Sparkles/></div><h2>Helpful, not diagnostic.</h2><p>Ask about records, missing information, or claim preparation. Gemini should not replace veterinary care.</p></div>{!messages.length&&<div className="prompt-list">{prompts.map(p=><button key={p} onClick={()=>send(p)}><Sparkles size={16}/>{p}<ChevronRight size={16}/></button>)}</div>}<div className="message-list">{messages.map((m,i)=><div className={m.role==='user'?'message user-message':'message'} key={i}>{m.text}</div>)}{busy&&<div className="message">Thinking...</div>}</div><div className="composer"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={pet?'Ask about your pet documents...':'Add a pet to personalize the assistant'} disabled={!pet||busy}/><button onClick={()=>send()} disabled={!pet||busy}><Bot size={18}/></button></div></div>}
function Empty({title,text}){return <div className="empty-inline"><div className="empty-illustration"><PawPrint size={22}/></div><div><b>{title}</b><p>{text}</p></div></div>}
function PetModal({onClose,onSave}){const [name,setName]=useState('');const [species,setSpecies]=useState('Dog');const [breed,setBreed]=useState('');const [dob,setDob]=useState('');const [insurance,setInsurance]=useState('');const [image,setImage]=useState(DOG_IMAGE);const age=dob?getAge(dob):'';return <div className="overlay"><div className="modal"><button className="close" onClick={onClose}><X/></button><span className="eyebrow">NEW PET</span><h2>Create a pet profile</h2><div className="pet-picker"><img src={image} alt="Pet"/><button onClick={()=>setImage(image===DOG_IMAGE?CAT_IMAGE:DOG_IMAGE)}>Change photo</button></div><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Milo"/></label><label>Species<select value={species} onChange={e=>setSpecies(e.target.value)}><option>Dog</option><option>Cat</option><option>Other</option></select></label><label>Breed <span>(optional)</span><input value={breed} onChange={e=>setBreed(e.target.value)} placeholder="e.g. Labrador"/></label><label>Date of birth <span>(optional)</span><input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><label>Insurance provider <span>(optional)</span><input value={insurance} onChange={e=>setInsurance(e.target.value)} placeholder="e.g. Petplan"/></label><button className="primary full" disabled={!name.trim()} onClick={()=>onSave({id:Date.now(),name:name.trim(),species,breed:breed.trim(),dob,ageText:age,insuranceProvider:insurance.trim(),image})}><Plus size={18}/> Save pet</button></div></div>}
function getAge(dob){const d=new Date(dob);const now=new Date();let y=now.getFullYear()-d.getFullYear();let m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))y--;return y<1?'Under 1 year':`${y} year${y===1?'':'s'}`}

createRoot(document.getElementById('root')).render(<App/>);
